### ISSUE TITLE
Symbol Table Pretty Formatting

### ISSUE THREAD

**Issue by kvrigor** [kvrigor/SymbolTableSimulator#5]
Sane table formatting would be nice for human consumption .. Refer to [here](/kvrigor/SymbolTableSimulator/blob/master/SymbolTableSimulator.cpp#L181)

**Comment by chesterlbtan** [comment]
done using below method

#include<iomanip>
#include<stdio.h>
	<<std::left<<std::setw(18)<<std::setfill(' ')<<data
