### ISSUE TITLE
Allow User to inject different amount of data

### ISSUE THREAD

**Issue by chesterlbtan** [kvrigor/SymbolTableSimulator#7]
I already created a list of new CSV files (with different amount of data) to be loaded depending on the user input.

**Comment by kvrigor** [comment]
@chesterlbtan How about we generate a master dataset containing, say 1M elements? We could then simply extract a subset from it when testing the algorithms. The subset will have user-specified # of elements which will be taken randomly from the master dataset.

**Comment by kvrigor** [comment]
This will allow us to easily profile the search, insert, and delete operations according to the desired table size without readjusting/regenerating dataset files every time.
